bcgov/parks-data-register

- pdr-api/handlers/config/GET/index.js
- pdr-api/handlers/parks/$identifier/name/GET/index.js
- pdr-api/handlers/parks/names/GET/index.js
- pdr-api/layers/base/base.js
- pdr-api/layers/dynamodb/dynamodb.js
- pdr-api/template.yaml
Resolves #23.
This change introduces a couple of park name endpoints for the API.
To if you know the `identifier` (pk, parkID, orcs) for the park you are looking up, use the endpoint:
`/park/{identifier}/name` 
to get the relevant name data. Add `status=current` as a query param to get the most up to date name.
If you do not know the specific park, there is an endpoint for name data for all parks at
`/parks/names`
where you must provide at least one of two query parameters:
- `status=current`: get the list of current park names
- `legalName={legalName}`: search by legal name
Ex:
`/park/1/name?status=current` will give the current name for ParkID 1 (Strathcona Park)
`/parks/names?status=current` will get you a list of all current names.
Testing files and Postman in progress.
Note: There …
> PDR-23 park names api part 1

- pdr-api/handlers/authorizer/index.js
- pdr-api/handlers/config/GET/index.js
- pdr-api/handlers/parks/_identifier/name/GET/index.js
- pdr-api/handlers/parks/names/GET/index.js
- pdr-api/layers/dynamodb/dynamodb.js
- pdr-api/layers/permissions/permissions.js
- pdr-api/postman/Parks Data Register.postman_collection.json
- pdr-api/template.yaml
features #137 
This ticket is to add Lambda Authorizers to our deployment.
At the moment, we have the ability to set authorizers on endpoints. In the case of current state, the config endpoint does not have an authorizer.
When a user sends a request to an endpoint that requires authorization, the request is first sent to our authorizer. The authorizer determines if a bearer token is provided from Keycloak. If that is the case, the token will be decoded to figure out if the user is actually authenticated. The authentication status is reflected in the context returned by the authorizer.
Each Lambda at the moment uses the content of the context to determine what to send back to the user. In the current cases, public users are not allowed to see pending park names.
> API-137: Adding preliminary authorizers to APIGW.

- .github/workflows/deploy-api-dev.yaml
- .github/workflows/deploy-api-prod.yaml
- .github/workflows/deploy-api-test.yaml
- pdr-api/.gitignore
- pdr-api/handlers/authorizer/index.js
- pdr-api/layers/dynamodb/dynamodb.js
- pdr-api/layers/permissions/permissions.js
- pdr-api/package.json
- pdr-api/template.yaml
SSO urls are now injected during deployment via GitHub Actions variables. 
Note: With AWS SAM, the local docker container that runs it is self contained and has no concept of local environment variables. when running `sam local start-api` all local env vars must be provided in the `template.yaml`. Env vars can be overwritten via an `env.json` file that might look something like this:
```json
{
"Parameters": {
"IS_OFFLINE": true, # mandatory
"TABLE_NAME": "NameRegister",
"AWS_REGION": "local-env",
"AWS_ENDPOINT_URL": "http://172.17.0.1:8000" # dynamodb docker container address
}
}
```
Locally, run `sam build --env-vars env.json` (or `yarn build` has this automagically built in) to overwrite the vars in `template.yaml` with the contents of your own `env.json`.
> setting SSO Realm vars for each env

- pdr-api/__tests__/settings.js
- pdr-api/__tests__/setup.js
- pdr-api/handlers/authorizer/index.js
- pdr-api/package.json
The previous authenticator lambda would generate permission policies based on the `methodArn` supplied with the event, then cache the user's successful authentication so repeated authentication was not necessary within the 300s caching window. Unfortunately the `methodArn` included the HTTP method and the subroute associated with the call, so the granted permissions were only for the first subroute called by the user. For future requests, authentication was skipped due to caching, and denied for any other subroute other than the one from the first request.
The authenticator will now attempt to trim off the HTTP method and subroute from the `methodArn` before generating a policy, instead allowing for a wildcard policy to be generated for all API gateway endpoints.
This methodology will …
> PDR-167 allowing policy generation for all endpoints at once

- .github/workflows/deploy-api-dev.yaml
- .github/workflows/deploy-api-prod.yaml
- .github/workflows/deploy-api-test.yaml
- pdr-api/template.yaml
Fixes #191 
Added env vars for dev/test/prod so that we can substitute the account id in the github workflow so that perms are working across items in the environment.
> 191: Fixing misaligned account ids in envs.

- pdr-api/handlers/authorizer/index.js
This fixes an issue where the authorizer was being called and cached for public users only at a specific endpoint.
> NOBUG: Update authorizer to allow all routes for public user.

- pdr-api/handlers/search/index.mjs
Filters added for Search by type and status (API SIDE ONLY).
Needs to be tested via postman.
https://github.com/bcgov/parks-data-register/issues/26
> PDR-26: filters added to api

- pdr-api/postman/Parks Data Register - DEV.postman_environment.json
- pdr-api/postman/Parks Data Register - LOCAL.postman_environment.json
- pdr-api/postman/Parks Data Register -TEST.postman_environment.json
- pdr-api/postman/Parks Data Register.postman_collection.json
This change adds `x-api-key` as a header to all current endpoints that necessitate a key. The header will reference an environment variable that contains the correct key, in a way that keeps the key a secret.
If you want to send an api key with your requests, the `x-api-key` header is now enabled by default on all requests that need an api key. If you want to remove `x-api-key` from the headers, simple disable (uncheck) the header. Do not delete it entirely. Environment variable files have now been updated with an EMPTY `x-api-key` variable. It is up to the developer to populate this field. Instructions on how to do this follow:
1.  Go into each environment variable file and update the key's CURRENT VALUE to the API key they wish to use. Leave the initial value cell blank.
2. Set the …
> NOBUG - adding x-api-key functionality to postman

- pdr-api/docs/dbModel.json
- pdr-api/docs/nosqlWorkbenchDataModel.json
- pdr-api/migrations/2023-11-24_updateEstablishedStatus.js
- pdr-api/tools/dataLoad.js
- pdr-api/tools/dynamoRestore.js
- pdr-api/tools/progressIndicator.js
Relates to #224.
This change adds a migration folder to `pdr-api` with a migration to perform the following updates on the DB:
- status `current` becomes status `established`
- status `old` becomes status `historical`
- all items (except `config`) now have type `protectedArea`
This change updates the `dataLoad.js` script to include the proper statuses and the `type` attribute.
The data model has been updated accordingly.
`dynamoRestore,js` and `progressIndicator.js` have been added to the tools folder for future use. 
Updates to the existing endpoints to accommodate these changes will follow in a future ticket.
> PDR-224-1 migration + data model change to update PA state and type

- pdr-api/docs/nosqlWorkbenchDataModel.json
One more minor change to the data model to reflect the changes in #239. Adding a changelog item for a repealed park. Adding attributes for `newLegalName`, `newEffectiveDate`, and `newStatus`.
> PDR-224 data model to include changelog item for repeal

- pdr-api/docs/nosqlWorkbenchDataModel.json
- pdr-api/migrations/2023-12-06_addDisplayIdField.js
Fixes #264.
Migration adds field `displayId` to the data model - `displayId` is the 4-digit leading zero padded pk.
> PDR-264 adding displayId field

- pdr-admin/src/app/services/url.service.ts
grabbing params from the constructor instead of ngoninit
> Url param lifecycle fix

- pdr-api/handlers/parks/_identifier/name/PUT/index.js
- pdr-api/handlers/parks/_identifier/name/__tests__/put.test.js
Fixes #292
Prevent major changes from happening if the request body does not include a new, different `legalName` from the existing current record.
If the major change is a status change, ie, repealed, allow the change to happen regardless of the `legalName` field.
> PDR-292 prevent major change without legalName change

- pdr-api/handlers/dynamoStream/index.js
Fixes #299 
The dynamoStream lambda that updates the OpenSearch index would bork if the notes field was empty on either the old or new indexed item. Adding conditionals to avoid more borking.
> PDR-299 fix OS indexing issue

- pdr-admin/src/app/protected-area/protected-area-search/protected-area-search.component.html
- pdr-admin/src/app/protected-area/protected-area-search/protected-area-search.component.ts
- pdr-admin/src/app/services/api.service.ts
- pdr-admin/src/app/services/search.service.ts
- pdr-admin/src/app/utils/constants.ts
Fixes #295
Adding `Load More` button to protected area search. 
Default page size is 20 items - this can be changed to whatever. 
Load more will bring in the next 20 items and appending them to the existing results until there are no more results to bring in.
> PDR-295-2 Adding loadmore button

- pdr-api/README.md
Adding instructions on how to install OpenSearch Dashboards locally.
> README: Locally install OS Dashboards

- pdr-api/docs/nosqlWorkbenchDataModel.json
- pdr-api/handlers/changelog/search/index.js
- pdr-api/handlers/parks/_identifier/name/PUT/index.js
- pdr-api/handlers/search/index.js
- pdr-api/layers/__tests__/opensearch.test.js
- pdr-api/layers/opensearch/opensearch.js
- pdr-api/postman/Parks Data Register.postman_collection.json
- pdr-api/template.yaml
Relates to #230 
Adds an endpoint `/changelog/search` to provide an easy way for the front end to collect changelog items. The endpoint hits the same `main-index` as the root `/search` function but has some added functionality specific to changelog searches - for example, it hardcodes `status=historical` such that the items the search returns will only be changelog items. 
The endpoint does not necessitate a text search. 
The ticket calls for results to be sorted by system date.
```
GET .../changelog/search?sortField=updateDate&sortOrder=desc
```
```
GET .../changelog/search?changeType=statusChanged
```
```
GET .../changelog/search?changeType=legalNameChanged
```
```
GET .../changelog/search?changeType=legalNameChanged,statusChanged
```
> PDR-230-2 adding /changelog/search endpoint

- pdr-api/layers/opensearch/opensearch.js
Sort order was broken due to several necessary variables not being initialized in the correct order.
> PDR-230 OSQuery constructor OOO change

- pdr-admin/src/app/change-log/change-log.component.html
- pdr-admin/src/app/change-log/change-log.component.scss
- pdr-admin/src/app/change-log/change-log.component.spec.ts
- pdr-admin/src/app/change-log/change-log.component.ts
- pdr-admin/src/app/protected-area/protected-area-search/protected-area-search.component.ts
- pdr-admin/src/app/services/changelog.service.spec.ts
- pdr-admin/src/app/services/changelog.service.ts
- pdr-admin/src/app/services/url.service.ts
- pdr-admin/src/app/utils/constants.ts
Completes #31
This change adds a changelog search to the front end. As per the ticket, the first 20 results are loaded in descending chronological order when landing on the page. Filtering by text or by statusChanged or legalNameChanged is also possible.
Note that only changelog items that have been created after #318 was merged will have the correct structure to appear properly in the changelog search. If there are existing changelog items that should be shown, we should create a new ticket to migrate them to the proper format.
> PDR-31 view changelog

- pdr-admin/src/app/protected-area/protected-area-search/protected-area-search.component.ts
- pdr-admin/src/app/utils/utils.spec.ts
Fixes #329.
Search results were being appended to existing results. Now when the search button is clicked, the previous search is wiped and a new search is performed. If the load more button is clicked, the results are still appended.
Also fixed some unit tests that were failing due to timezone differences.
> PDR-329 Clear search results when performing a new test

- pdr-api/__tests__/mock_data.js
- pdr-api/handlers/parks/_identifier/name/__tests__/get.test.js
- pdr-api/handlers/parks/_identifier/sites/GET/index.js
- pdr-api/handlers/parks/_identifier/sites/__tests__/get.test.js
- pdr-api/handlers/parks/names/__tests__/get.test.js
- pdr-api/layers/__tests__/dynamodb.test.js
- pdr-api/migrations/2024-02-29_updateSiteObj.js
- pdr-api/postman/Parks Data Register.postman_collection.json
- pdr-api/template.yaml
One of many PRs for:
https://github.com/bcgov/parks-data-register/issues/332
- Adding endpoint to get park site objects
- Migration added to include display name on park site objects
- Tests updated
- Postman updated
- SAM template updated
> 332: Adding get for park site objs.

- pdr-admin/src/app/protected-area/protected-area-manage/protected-area-edit-form/protected-area-edit-form.component.html
- pdr-admin/src/app/protected-area/protected-area-manage/protected-area-edit-form/protected-area-edit-form.component.ts
- pdr-admin/src/app/protected-area/protected-area-manage/protected-area-edit-repeal/protected-area-edit-repeal.component.ts
- pdr-admin/src/app/protected-area/protected-area-manage/protected-area-manage-routing.module.ts
- pdr-admin/src/app/protected-area/protected-area-manage/protected-area-manage.component.html
- pdr-admin/src/app/protected-area/protected-area-manage/protected-area-manage.component.scss
- pdr-admin/src/app/protected-area/protected-area-manage/protected-area-manage.component.ts
- pdr-admin/src/app/protected-area/protected-area-search/protected-area-search.component.html
- pdr-admin/src/app/protected-area/protected-area-search/protected-area-search.component.scss
- pdr-admin/src/app/services/loading.service.ts
- pdr-admin/src/app/shared/name-header/name-header.component.html
Relates to #412 
Removing intermediate `edit` forking page from protected areas routing, replaced with dropdown on root page now.
Removing view/edit icons from search results table.
Routing updates - navigating to `/repeal` or `/major` edit types when the protected area is repealed will now redirect you back to the search page with an error toast.
> PDR-412 FE updates for PAs

- pdr-api/template.yaml
PUT was missing from `ApiDeployment::Properties::Cors::AllowMethods` in `template.yaml`.
> NOBUG adding PUT as allowable CORS method for local development

- pdr-api/__tests__/mock_data.js
- pdr-api/__tests__/settings.js
- pdr-api/handlers/parks/_identifier/name/PUT/index.js
- pdr-api/handlers/sites/_identifier/PUT/index.js
- pdr-api/layers/__tests__/dynamodb.test.js
- pdr-api/layers/__tests__/siteUtils.test.js
- pdr-api/layers/awsUtils/dynamodb.js
- pdr-api/layers/awsUtils/nodejs/package.json
- pdr-api/layers/base/base.js
- pdr-api/layers/base/nodejs/package.json
- pdr-api/layers/base/permissions.js
- pdr-api/layers/dataUtils/data-constants.js
- pdr-api/layers/dataUtils/nodejs/package.json
- pdr-api/layers/dataUtils/siteUtils.js
- pdr-api/package.json
- pdr-api/postman/Parks Data Register.postman_collection.json
- pdr-api/template.yaml
Relates to #407 
Adds site PUT endpoint to API. Behaves analogously to the Protected Area Names PUT endpoint.
Employs new design philosophy of keeping the lambda handlers very lean, and moving logic based code to a layer.
> PDR-407 Sites PUT

- pdr-api/handlers/parks/_identifier/name/PUT/index.js
- pdr-api/layers/dataUtils/siteUtils.js
Relates to #326
When repealing a protected area, the system now creates a transaction to repeal the child sites at the same time. All transactions are run together (up until the transaction item limit of 100, at which point the transactions are performed in groups of at most 100).
> PDR-326 repeal all child sites when repealing protected area

- pdr-admin/src/app/protected-area/protected-area-manage/protected-area-edit-form/protected-area-edit-form.component.ts
- pdr-admin/src/app/protected-area/protected-area-manage/protected-area-manage-routing.module.ts
- pdr-admin/src/app/protected-area/protected-area-manage/protected-area-manage.component.html
- pdr-admin/src/app/protected-area/protected-area-manage/protected-area-manage.component.ts
- pdr-admin/src/app/shared/edit-form/edit-form.html
In both protected-areas and sites, there were some extraneous fields present when repealing or editing a repealed record. This change ensures that only the effective date field is present when repealing or editing a repealed record as per the designs.
> PDR-402-2 removing notes field as per designs

- pdr-admin/src/app/protected-area/site/site-manage/site-edit-form/site-edit-form.component.ts
Fixes #452.
Not a datepicker issue so much as a lazy loading issue. The datepicker rendering changes but the old rendering is not removed. Patched in a similar way to protected areas - `detectChanges` wrapped in a 0s timeout.
> PDR-452: lazy loading causing issues with site datepicker

- pdr-admin/package.json
- pdr-admin/src/app/shared/name-header/name-header.component.html
- pdr-admin/yarn.lock
Relates to #332.
Record type (Protected Area) was hardcoded in the header. Now record type is dynamic (Site or Protected Area).
Also bumped NGDS-Forms to v0.0.110 to fix a small issue where invalid fields where simply displaying the text 'true' when they were invalid instead of the more informative defaults.
> PDR-332-1 showing correct datatype in header

- pdr-admin/src/app/services/protected-area.service.ts
Before, the protected area service prevented any `edits` unless the edit type was major or minor. There was a separate function for the repealed type and the edit-repeal was considered a minor edit.
With the changes implemented with the new sites features, the `edit-repeal` update type is now distinct so must also be included in the types of edits allowed in the protected area service.
> PDR-326 fixing allowed updateTypes for PAs

- pdr-admin/src/app/services/protected-area.service.ts
Relates to #332 
Must convert `edit-repeal` updateType to `minor` before passing to API.
> PDR-332 fixing repeal edit for protected areas

- .vscode/settings.json
Adding a `settings.json` file to synchronize formatting settings between `vscode` contributors to the project. Theoretically if this is included in your workplaces, the workplace formatting settings should override user settings - https://code.visualstudio.com/docs/getstarted/settings, but we need to confirm that it actually does function in this way & that the folder is saved in the right place.
> NOBUG - Adding settings.json formatting file

- pdr-admin/src/app/change-log/change-log.component.html
- pdr-admin/src/app/protected-area/protected-area-manage/protected-area-manage.component.ts
- pdr-admin/src/app/protected-area/protected-area-search/protected-area-search.component.html
Resolves #334 
Changing the UI to remove leading 0's in ORCS. 
Removed in search results, changelog results, and details pages. Couldn't find other places where it was displayed.
> PDR-334 remove leading zeroes from ORCS in UI

- pdr-admin/package.json
- pdr-admin/yarn.lock
Temporarily resolves https://github.com/bcgov/parks-data-register/issues/564. 
Upgrades to `keycloak-js@25.0.6` instead of the recommended `keycloak-js@26.2.0`. Will need to bump the angular version before upgrading to the recommended version.
> DR-564: temporary fix to keycloak-js dependency

- pdr-api/__tests__/mock_data.js
- pdr-api/handlers/fees/DELETE/index.js
- pdr-api/handlers/fees/POST/index.js
- pdr-api/handlers/fees/_tests_/delete.test.js
- pdr-api/handlers/fees/_tests_/post.test.js
- pdr-api/template.yaml
Ticket: [559](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=93717255&issue=bcgov%7Cparks-data-register%7C559)
Notes: 
- Add validation for chargeBy attributes and improve DELETE/POST handlers
- Added `FEES_OPTIONAL_PUT_FIELDS` validation to ensure only valid `chargeBy` attributes are allowed in POST and DELETE handlers.
- Updated `deleteParameter` to handle cases where the last `chargeBy` attribute cannot be deleted.
- Improved error handling in DELETE handler to return appropriate responses for missing or invalid items.
- Added new test cases for DELETE handler:
- Prevent deletion of the last `chargeBy` attribute.
- Handle invalid `chargeBy` attributes.
- Handle missing fee records.
- Fixed test data and mock configurations for consistency.
- Updated `template.yaml` …
> BRS-559: Fee Register send back fixes for DELETE

- pdr-api/handlers/fees/DELETE/index.js
- pdr-api/handlers/fees/_tests_/delete.test.js
Ticket: [559](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=93717255&issue=bcgov%7Cparks-data-register%7C559)
Notes: Sending responses from within functions was causing problems when in an AWS environment. Have refactored the code to send all responses from main handler function. Picture of error below for reference incase  this ever happens again.
> BRS-559: Fee Register Delete Fixes
