bcgov/parks-data-register

pdr-api/docs/nosqlWorkbenchDataModel.json

This is the initial model to be used for the parks register back-end.  This file can be imported in [NoSQL Workbench](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/workbench.settingup.html) and used to query, manipulate and extend the data model.  This file is meant to be kept up-to-date with the database model as it changes.  Only primitive sample data is provided in the model file.
The name of the data model, which is "Name Data Register".
Contains metadata about the model, including author, creation and modification dates, description, AWS service used (Amazon DynamoDB), and version.
This is the main section that defines the data model's structure and attributes.
The name of the table in DynamoDB, which is "OrcsData".
Specifies the primary key attributes for the …

API-33: Create Data Model for Name Register

---

pdr-api/docs/nosqlWorkbenchDataModel.json

Updated the data register model to reflect changed pk/sk requirements.
Added audit table
Fixes #33 and #34

PDR-33: Updated primary model for the name register. Added audit table.

---

CODEOFCONDUCT.md
README.md
pdr-admin/README.md
pdr-api/README.md

https://github.com/bcgov/parks-data-register/issues/48

PDR-48: addition of CODEOFCONDUCT and updates to READMEs

---

bcgovpubcode.yml

PDR-47: Added initial pubcode reference.

---

pdr-api/postman/Parks Data Register - DEV.postman_environment.json
pdr-api/postman/Parks Data Register - LOCAL.postman_environment.json
pdr-api/postman/Parks Data Register -TEST.postman_environment.json
pdr-api/postman/Parks Data Register.postman_collection.json

Resolves #23. 
Adding postman env setup for `parks/names` and `parks/{identifier}/name`

PDR-23 Postman setup

---

pdr-api/handlers/authorizer/index.js

`token.sid` should be `token.data.sid`

NOBUG token.data.sid

---

.github/workflows/on-pr-api.yaml

Adding github actions trigger to run API tests on PR creation.
Note = #142 must be merged first.

PDR-23 adding API tests to PR workflow

---

pdr-api/template.yaml

Adding CORS configuration

---

pdr-admin/angular.json
pdr-admin/src/app/manage-records/manage-records.component.html
pdr-admin/src/app/manage-records/manage-records.component.spec.ts
pdr-admin/src/app/manage-records/manage-records.component.ts
pdr-admin/src/app/services/api.service.ts
pdr-admin/src/app/services/search.service.ts
pdr-admin/src/app/utils/constants.ts
pdr-admin/src/env.js
pdr-api/template.yaml

TODO:
-Filtering (will create another PR to keep API changes separate) 
-Feedback/button functionality (covered by https://github.com/bcgov/parks-data-register/issues/27)

PDR-26: Search functionality implemented.

---

.github/workflows/deploy-admin-dev.yaml
.github/workflows/deploy-admin-prod.yaml
.github/workflows/deploy-admin-test.yaml
pdr-admin/template.yaml

Relates to #10 
Part 1 - adding SAM template for pdr-admin vanity urls + SSL certificates.

PDR-10 Vanity Url + Cert for Admin

---

pdr-api/template.yaml

This fixes an errant deployment issue.

NOBUG: Fix incorrect template configuration for CORS.

---

pdr-api/handlers/authorizer/index.js
pdr-api/template.yaml

NB: This requires api keys to be generated and used for each environment/consumer of the api including the front-end.

122: Updated authorized, added usage plan, enforce api keys.

---

.github/workflows/deploy-admin-dev.yaml
.github/workflows/deploy-admin-prod.yaml
.github/workflows/deploy-admin-test.yaml
pdr-admin/template.yaml

Updating the SAM template to include vanity URL provisions. 
Updated API CF caching policy to allow 'Authorization' and 'X-Api-Key' headers.

PDR-10 adding vanity url for API and Admin

---

pdr-api/handlers/parks/_identifier/name/PUT/index.js

During PUT, if no value provided for `displayName`, the `displayName` is populated with the value of the `legalName` field. If either the `legalName` or the `effectiveDate` fields are blank, throw an error.

PDR-249 cannot pass blank values on some mandatory fields

---

pdr-api/handlers/search/index.mjs

fixes an issue where any filtered items containing capital letters return no results

NOBUG: fix for search endpoint capitalization issue

---

pdr-api/handlers/parks/_identifier/name/PUT/index.js
pdr-api/handlers/parks/_identifier/name/__tests__/put.test.js

Adding a conditional check on park name PUT. For any updateType (minor, major, repeal), you must now provide the `lastVersionDate` property in the payload. `lastVersionDate` equals the `updateDate` property of the `established` protected area object, as the `updateDate` gets updated with every edit change.
If the `lastVersionDate` field is not provided, or if it does not match the `updateDate` property on the existing protected area record, the API will return 400. Transactions including the put will be cancelled.

PDR-249-3 enforcing record versioning

---

pdr-api/handlers/dynamoStream/index.js

Note: This only updates the stream processor.  An additional migration / script will be required to update the existing index. This will ensure moving forward we're not adding the notes field to the OS index.
This also fixes a date issue with the sk on the OS image.

248: Remove searching notes field.

---

pdr-admin/src/app/protected-area/protected-area-search/protected-area-search.component.spec.ts
pdr-admin/src/app/protected-area/protected-area-search/protected-area-search.component.ts
pdr-admin/src/app/services/data.service.ts
pdr-admin/src/app/services/search.service.ts
pdr-admin/src/app/services/url.service.ts

Url service added now - matches url queryparams to search query on the search page. 
Basic search caching implemented in protectedarea route - when landing on the page via a browser history navigate, the cache is checked and if there is a hit, the front end is updated with the cache instead of calling the API. Default cache expiry has been set to 5 mins.

NOBUG adding url service and basic caching

---

pdr-admin/src/app/protected-area/protected-area-manage/protected-area-manage.component.ts
pdr-admin/src/app/protected-area/protected-area-search/protected-area-search.component.html
pdr-admin/src/app/protected-area/protected-area-search/protected-area-search.component.scss
pdr-admin/src/app/services/protected-area.service.ts

ProtectedAreaManageComponent calls clearCurrentProtectedArea() on OnDestroy.

NOBUG unload cached PAs on change and UI fix

---

pdr-api/handlers/search/index.mjs

Relates to #295 
Adding queryParams to the `/search` endpoint so that the results can be controlled for size and pagination.
By default, the `/search` endpoint will return 10 results. You can specify a different number of results to return using the `limit` query param. The default limits for `limit` are 1 <= `limit` <=100.
By default, `/search` will return results starting from the first result it finds. You can pseudo paginate by changing the `startFrom` param. If you provide a value for `startFrom`, `/search` will skip that many results and start returning from the next result.
ie: `startFrom=10` => `/search` will skip the first 10 results and start returning from result 11.
Note: when we start incorporating `sort` into our opensearch queries we will need to take a slightly more robust …

PDR-295-1 api to support query limits and basic pagination

---

pdr-api/handlers/parks/_identifier/name/PUT/index.js
pdr-api/handlers/parks/_identifier/name/__tests__/put.test.js

Fixes #304 
Removing the API requirements to provide every field when doing a protectedArea PUT. Now, only mandatory and relevant fields are required:
- lastVersionDate
- effectiveDate
- legalName (major change only)
- legalName (minor change only)
- displayName
- searchTerms
- audioClip
- notes
- phoneticName
Logic has changed drastically, @manuji most likely a full retest of the PUT endpoint is required.

PDR-304 protectedArea put only requires relevant fields

---

.github/workflows/deploy-admin-dev.yaml
.github/workflows/deploy-admin-prod.yaml
.github/workflows/deploy-admin-test.yaml

105: Invalidate CF during deploys

---

pdr-api/handlers/parks/_identifier/name/PUT/index.js

changelog items saving user field as `User`. Should be `lastModifiedBy`.

NOBUG change lastModifiedBy

---

pdr-admin/src/app/change-log/change-log.component.html
pdr-admin/src/app/change-log/change-log.component.scss
pdr-admin/src/app/change-log/change-log.component.ts
pdr-admin/src/app/services/changelog.service.ts

PDR-345 Go to PA details page on changelog item click

---

pdr-admin/src/app/protected-area/protected-area-manage/protected-area-details/protected-area-details.component.html
pdr-admin/src/app/protected-area/protected-area-manage/protected-area-edit-form/protected-area-edit-form.component.html
pdr-admin/src/app/protected-area/protected-area-manage/protected-area-edit-form/protected-area-edit-form.component.ts

Adding temp notes field.
https://github.com/bcgov/parks-data-register/issues/175

DR-175: Adding temp notes field

---

pdr-api/docs/nosqlWorkbenchDataModel.json
pdr-api/migrations/2024-02-08_addSites.js

Updated model and migration script (to be run on prod)

PDR-125: sites migration

---

pdr-api/migrations/2024-02-08_addSites.js

Small update to import for any future additions

PDR-125: update to displayId and updateDate to match dynamo

---

pdr-admin/src/app/protected-area/protected-area-manage/protected-area-details/protected-area-details.component.html
pdr-admin/src/app/protected-area/protected-area-manage/protected-area-details/protected-area-details.component.spec.ts
pdr-admin/src/app/protected-area/protected-area-manage/protected-area-manage-routing.module.ts
pdr-admin/src/app/protected-area/protected-area-manage/protected-area-manage.component.html
pdr-admin/src/app/protected-area/protected-area-manage/protected-area-manage.component.ts
pdr-admin/src/app/protected-area/protected-area-manage/protected-area-manage.module.ts
pdr-admin/src/app/protected-area/site/site-list/site-list.component.html
pdr-admin/src/app/protected-area/site/site-list/site-list.component.spec.ts
pdr-admin/src/app/protected-area/site/site-list/site-list.component.ts
pdr-admin/src/app/protected-area/site/site-manage/site-manage.component.html
pdr-admin/src/app/protected-area/site/site-manage/site-manage.component.spec.ts
pdr-admin/src/app/protected-area/site/site-manage/site-manage.component.ts
pdr-admin/src/app/protected-area/site/site-routing.component.ts
pdr-admin/src/app/protected-area/site/site.component.html
pdr-admin/src/app/protected-area/site/site.component.spec.ts
pdr-admin/src/app/protected-area/site/site.component.ts
pdr-admin/src/app/protected-area/site/site.module.ts
pdr-admin/src/app/services/breadcrumb.service.ts
pdr-admin/src/app/services/protected-area.service.ts
pdr-admin/src/app/services/site.service.spec.ts
pdr-admin/src/app/services/site.service.ts
pdr-admin/src/app/shared/name-header/name-header.component.html
pdr-admin/src/app/shared/name-header/name-header.component.spec.ts
pdr-admin/src/app/shared/name-header/name-header.component.ts
pdr-admin/src/app/shared/shared.module.ts
pdr-admin/src/app/utils/constants.ts

Relates to #394.
This stubs out the routing that will be used for the view sites details page. The API to get sites details is not yet ready so there will be no information on the sites details page but the routing is correct.

PDR-394 stubbing out sites routing

---

pdr-admin/src/app/protected-area/protected-area-manage/protected-area-edit-form/protected-area-edit-form.component.ts
pdr-admin/src/app/protected-area/protected-area-manage/protected-area-edit-repeal/protected-area-edit-repeal.component.ts

Relates to #412. Fixed a few bugs.

PDR-412-2 fixing errors on PUT actions

---

pdr-admin/src/app/protected-area/protected-area-manage/protected-area-edit-repeal/protected-area-edit-repeal.component.ts

this is gonna work first try baby

cancel nav from repeal

---

pdr-admin/src/app/protected-area/protected-area-manage/protected-area-edit-repeal/protected-area-edit-repeal.component.ts

this one is first try also, the last one was a different issue I swear

PDR-412-3 routing fix 3

---

pdr-admin/src/app/guards/dynamic-redirect.guard.ts
pdr-admin/src/app/protected-area/protected-area-manage/protected-area-details-section/protected-area-details-section.component.html
pdr-admin/src/app/protected-area/protected-area-manage/protected-area-details-section/protected-area-details-section.component.ts
pdr-admin/src/app/protected-area/protected-area-manage/protected-area-details/protected-area-details.component.html
pdr-admin/src/app/protected-area/site/site-manage/site-details/site-details.component.html
pdr-admin/src/app/protected-area/site/site-manage/site-details/site-details.component.spec.ts
pdr-admin/src/app/protected-area/site/site-manage/site-details/site-details.component.ts
pdr-admin/src/app/protected-area/site/site-manage/site-manage.component.html
pdr-admin/src/app/protected-area/site/site-manage/site-manage.component.ts
pdr-admin/src/app/protected-area/site/site-routing.component.ts
pdr-admin/src/app/protected-area/site/site.module.ts
pdr-admin/src/app/services/site.service.ts
pdr-admin/src/app/shared/info-section/info-section-row/info-section-row.component.html
pdr-admin/src/app/shared/info-section/info-section-row/info-section-row.component.spec.ts
pdr-admin/src/app/shared/info-section/info-section-row/info-section-row.component.ts
pdr-admin/src/app/shared/info-section/info-section.component.html
pdr-admin/src/app/shared/info-section/info-section.component.spec.ts
pdr-admin/src/app/shared/info-section/info-section.component.ts
pdr-admin/src/app/shared/not-found/not-found.component.spec.ts
pdr-admin/src/app/shared/not-found/not-found.component.ts
pdr-admin/src/app/shared/shared.module.ts
pdr-admin/src/app/utils/constants.ts

PDR-395 adding site details page pt 1

---

pdr-api/yarn.lock

Updating dependencies to hopefully address security vulnerabilities
No breaking change dependencies according to `yarn upgrade-interactive`.

addressing security vulnerabilities in api

---

pdr-admin/package.json
pdr-admin/yarn.lock
pdr-api/yarn.lock

Updating dependencies to hopefully address security vulnerabilities. 
No breaking change dependencies according to `yarn upgrade-interactive`, mostly patches.

Addressing security vulnerabilities for admin

---

pdr-api/handlers/fees/PUT/index.js
pdr-api/handlers/fees/_tests_/feesPut.test.js

Ticket: [559](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=93717255&issue=bcgov%7Cparks-data-register%7C559)
Notes: Updating error message to be more clear.

559 - Fee-Register Fix

---

pdr-admin/src/app/footer/footer.component.html
pdr-admin/src/app/footer/footer.component.scss

Ticket: [492](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=91284780&issue=bcgov%7Cparks-reso-public%7C492)
Notes: There was no designs supplied for data register; this is a mix between the example and existing footer.

BRS-492: Added land acknowledgment to footer

---

pdr-api/handlers/fees/DELETE/index.js
pdr-api/handlers/fees/POST/index.js
pdr-api/handlers/fees/PUT/index.js
pdr-api/handlers/fees/_tests_/delete.test.js
pdr-api/handlers/fees/_tests_/feesPut.test.js

Notes: 
* changed DELETE endpoint to match naming conventions of the other endpoints (activity NOT service).
* Updated error messages for PUT endpoint to reflect all parameters used in query when failed.
* Added error message to POST endpoint for situation when PK SK already exists in db. 
* Updated tests to comply with these changes.

Fixes for fee reg
